// This file was generated by Prisma
import { defineConfig } from "prisma/config";

// Try to load dotenv, but don't fail if it's not available
try {
  require("dotenv/config");
} catch (error) {
  console.log("dotenv not available, skipping env loading");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma v7 with MariaDB adapter - using PrismaMariaDb adapter only
  // Database connection is managed by PrismaMariaDb adapter in lib/prisma.ts
  // DATABASE_URL environment variable will be used for operations
});