// This file was generated by Prisma
import { PrismaClient } from "@prisma/client";

// Provide a default datasource URL for Prisma operations
const DATABASE_URL = process.env.DATABASE_URL || "mysql://casn_user:casn_password123@mysql:3306/casn";

// Prisma v7 configuration
export const prisma = new PrismaClient({
  datasources: {
    db: {
      url: DATABASE_URL,
    },
  },
});

export default prisma;