// This file was generated by Prisma
import { defineConfig } from "prisma/config";

// Provide a default datasource URL for Prisma operations
const DATABASE_URL = process.env.DATABASE_URL || "mysql://casn_user:casn_password123@mysql:3306/casn";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Add datasource URL for Prisma operations
  datasourceUrl: DATABASE_URL,
  // Prisma v7 with MariaDB adapter - using PrismaMariaDb adapter only
  // Database connection is managed by PrismaMariaDb adapter in lib/prisma.ts
});