// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `mysql://${process.env.DB_USER || "casn_user"}:${process.env.DB_PASSWORD || "casn_password123"}@${process.env.DB_HOST || "mysql"}:${process.env.DB_PORT || 3306}/${process.env.DB_NAME || "casn"}?charset=utf8mb4`,
  },
});
