/* eslint-disable @typescript-eslint/no-explicit-any */
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getAuthorBySlug } from "@/lib/authors";
import Hero from "@/components/Hero";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;
export const fetchCache = "force-no-store";

// Metadata is generated by layout.tsx - no DB access in generateMetadata

// celowo: props:any – omijamy wadliwy constraint z .next/types
export default async function AuthorPage(props: any) {
  const { slug }: { slug: string } = await props.params;
  if (!slug) return notFound();

  const result = await getAuthorBySlug(slug);
  if (!result) return notFound();

  const { author, analyses } = result;

  // Bezpieczne funkcje pomocnicze
  const getAvatarSrc = (img?: string | null) =>
    img && (img.startsWith("/") || img.startsWith("http"))
      ? img
      : "/images/placeholder.png";

  return (
    <main>
      <Hero
        title={author.displayName}
        breadcrumbs={[
          { label: "Strona główna", href: "/" },
          { label: "Nasi autorzy", href: "/autorzy" },
          { label: author.displayName, active: true },
        ]}
      />

      <section className="section">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-4">
              <div className="team-details-img mo-mb-20">
                <Image src={getAvatarSrc(author.img)} alt={`Zdjęcie ${author.displayName}`}
                       className="img-fluid d-block mx-auto rounded" width={600} height={600} unoptimized />
              </div>
            </div>
            <div className="col-lg-8">
              <div className="team-details rounded p-4">
                <h4 className="text-dark mb-2">{author.displayName}</h4>
                <div className="team-details-border mt-3 mb-3"></div>
                <p className="team-details-desc text-muted mb-4">{String(author.bio ?? "")}</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {analyses.length > 0 ? (
        <section className="section bg-light">
          <div className="container">
            <div className="row">
              <div className="col-lg-6">
                <h3 className="text-dark">Artykuły</h3>
                <div className="team-details-border mt-3 mb-4"></div>
                <div className="activities-item mb-4">
                  {analyses.map((a) => (
                    <p className="mb-3" key={a.id}>
                      <i className="mdi mdi-checkbox-marked-circle-outline text-custom mr-2"></i>
                      <Link href={`/analizy/${a.slug}`}>{a.title}</Link>
                    </p>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>
      ) : null}
    </main>
  );
}